[package]
name = "HTLP"
version = "0.1.0"
authors = ["GuyWberg <guywberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modular = "1.0.0"
rand = "0.7"
num-integer = "0.1.44"
num-bigint-dig = "0.6.1"